name = "spinogambino-app-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-app.com.gr"
HMAC_KEY = "7365bb83d8b54572ec12a5a16ce85b948528c8c33bf8f9f2c400952b15581f30"
COOKIE_NAME = "2ee"
PLAY_PATH = "play"
BUTTON_ID = "p2297c75ea06e7a302a85e32abbddd876"
GATE_SALT = "cf8d810ab7f6a8a1"
